# Generated by Django 5.2.4 on 2025-07-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotV1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('info', models.TextField()),
                ('auth_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
