# Generated by Django 5.2.4 on 2025-07-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('idea', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
