# Generated by Django 5.1.4 on 2025-07-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('from_user', models.CharField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
